done
fs-jun24-team-3/React.ts-GroupProject pull request #24
Opened 2024-09-17 17:21 UTC by NIKaragu

2024-09-18 09:18 UTC, k-marchuk requested changes

2024-09-18 09:18 UTC, k-marchuk commented on src/api/api.ts
> +    .then(res => res.json());
According to the task description you should use asyncThunk

2024-09-18 12:07 UTC, NIKaragu commented on src/api/api.ts
> +    .then(res => res.json());
This part of code is responsiblle only for downloading data from server, `async thunk` is used only for receiving async funcs/callbacks and take `dispatch`  as parameters, `async thunk` don't work with remote server, `async thunk` should be used in comparing with redux store, but not with server

2024-09-18 12:33 UTC, k-marchuk commented on src/api/api.ts
> +    .then(res => res.json());
You can check lesson about asyncThunk to understand this requirement better

https://mate.academy/learn/redux/redux-toolkit?learnItemsFilter=All&section=theory&theoryId=402&videoId=3421&testTaskSlug=react-redux-list-of-posts#redux-thunk

2024-09-19 13:33 UTC, k-marchuk approved these changes

2024-09-19 13:34 UTC, merged