made dropdown layout
fs-jun24-team-3/React.ts-GroupProject pull request #34
Opened 2024-09-19 14:10 UTC by onikishyna

2024-09-19 14:43 UTC, SashaPas05 requested changes
The code looks good, but fix a **small** flaw

2024-09-19 14:43 UTC, SashaPas05 commented on src/components/Dropdown/Dropdown.module.scss
> +    ;
```
    border: $elemnts-color;
    ; //// Unnecessary
```

2024-09-19 15:23 UTC, SashaPas05 approved these changes
GJ!

2024-09-20 06:25 UTC, k-marchuk approved these changes

2024-09-20 06:25 UTC, merged