Feature/base structure for main component
fs-jun24-team-3/React.ts-GroupProject pull request #5
Opened 2024-09-13 19:26 UTC by NIKaragu

Created a base structure for Main component and also subcomponents for Main + made base styles for Main component.
Also was fixed structure of MainPage and its styles

2024-09-13 21:22 UTC, k-marchuk requested changes
Very nice work!
I left one suggestion.

2024-09-13 21:22 UTC, k-marchuk commented on src/components/Main/NewModelsList/NewModelList.tsx
> +    </div>
There are 2 components with such sliders on Main page (hot prices and brand new models), and one more on Item card page (you may also like). They all look identical, only content and headers differ. Maybe it makes sense to create only one component, something like ProductsSlider and reuse it?
More thoughts are needed :thinking:

2024-09-14 11:40 UTC, NIKaragu commented on src/components/Main/NewModelsList/NewModelList.tsx
> +    </div>
Good idea, done)

2024-09-14 12:53 UTC, k-marchuk commented
It is seems that you are working on implementing the Home Page, but we have a separate task for that in Step 5 https://app.clickup.com/t/86c0a7fx3. 
It's seems we have to clarify with Danylo what is main component.

2024-09-14 14:21 UTC, NIKaragu commented
> It is seems that you are working on implementing the Home Page, but we have a separate task for that in Step 5 https://app.clickup.com/t/86c0a7fx3. It's seems we have to clarify with Danylo what is main component.

Our MainPage is equal to HomePage, we can rename it later or adjust some moments according to next tasks. 
Just let's move on step by step with our current tasks, don't run ahead so far)

2024-09-14 15:28 UTC, merged